---
title: Op de eerste rij • Cultuureducatie
timezone: Europe/Amsterdam
collections:
  crew:
    title: Crew
    output: false
    author: info@opde1sterij.nl
    korte-beschrijving: De hele Op de eerste rij crew.
  posts:
    title: Posts
    output: true
    author: info@opde1sterij.nl
    korte-beschrijving: Elke zondag een nieuwe blog van de Op de eerste rij crew.
    assets:
    - path: "/uploads/elke-woensdag-een-nieuwe-blog.jpg"
      name: elke-woensdag-een-nieuwe-blog
    - path: "/uploads/blog.jpg"
      name: blog
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    zoektermen: 
    korte-beschrijving: 
    trailer-embed-code: 
    filmpje-embed-code: 
    home-page: 
    assets:
    - path: ''
      name: ''
- scope:
    path: ''
    type: posts
  values:
    layout: default
    permalink: "/blog/:i_day-:i_month-:year-:title/"
    blogger: 
    trailer-embed-code: 
    filmpje-embed-code: 
    assets:
    - path: ''
      name: ''
- scope:
    path: ''
    type: crew
  values:
    onderdeel: 
    blogger-bio: 
    assets:
    - path: ''
      name: ''
repository: opde1sterij/archived
url: https://www.opde1sterij.nl
permalink: pretty
markdown: kramdown
auteur: Op de eerste rij
include:
- ".gearchiveerd"
- ".2022-03"
- ".2022-04"
- ".2022-05"
- ".2022-06"
- ".2022-07"
- ".2022-09"
- ".2022-11"
plugins:
- jekyll-redirect-from
whitelist:
- jekyll-redirect-from
